kind: Deployment
metadata:
  name: memulesidecarinject
  namespace: glin-ap31312mp00875-dev-platform-namespace
  labels:
    app: memulesidecarinject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memulesidecarinject
  template:
    metadata:
      labels:
        app: memulesidecarinject
    spec:
      containers:
        - name: memulesidecarinject
          image: "sbenfa/sidecar-injector:latest"
          imagePullPolicy: Always
          args:
          - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
          - -tlsCertFile=/etc/webhook/certs/tls.crt
          - -tlsKeyFile=/etc/webhook/certs/tls.key
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-certs
        secret:
          secretName: memulesidecarinject-certificate
      - name: webhook-config
        configMap:
          name: sidecar-injector-webhook-configmap