kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentbit-configmap
data:
  PLATFORM_MODULE_ID: memulesidecarinject
  PLATFORM_LOG_LEVEL: DEBUG
  PLATFORM_MODULE_VERSION: 1.0.0
  PLATFORM_MODULE_DOMAIN: SLtraining
  ENV: dev
  CREATION_TIMESTAMP: 08-06-2021T23:59:59
  SERVERLESS_ROLE_EXECUTION: aaa
  # catalogUrl: catalog.glin-ap31312plmcatc-dev-platform-namespace.global
  CATALOG_URL: catalog.glin-ap31312plmcatc-dev-platform-namespace.global
  # commonEventUrl: events-dispatcher.glin-ap31312plmevnt-dev-platform-namespace.global
  EVENTS_URL: events-dispatcher.glin-ap31312plmevnt-dev-platform-namespace.global
  # schemaRegistryUrl: rest.glin-ap31312plcpksr-dev-platform-namespace.global:80/schemas/ids
  CONFLUENT_SCHEMA_REGISTRY_URL: rest.glin-ap31312plcpksr-dev-platform-namespace.global:80/schemas/ids
  # asyncResultUrl: result-mresc.glin-ap31312plmresc-dev-platform-namespace.global
  ASYNC_RESULT_URL: result-mresc.glin-ap31312plmresc-dev-platform-namespace.global
  ASYNC_RESULT_SCHEMA_ID: "25"
  AUDIT_SCHEMA_ID: "30"
  CONSUMER_POLL_MILLIS: "1000"
  AWS_TEST_CONNECTION_MAX_RETRIES: "30"