apiVersion: v1
kind: Service
metadata:
  name: memulesidecar
  namespace: glin-ap31312mp00875-dev-platform-namespace
  labels:
    app: memulesidecarinject
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: memulesidecarinject