apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  labels:
    app: sidecar-injector
webhooks:
- name: sidecar-injector.morven.me
  failurePolicy: Fail
  clientConfig:
    service:
      name: sidecar-injector-webhook-svc
      namespace: sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EVXlNVEl5TVRreE9Wb1hEVE14TURVeE9USXlNVGt4T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDZnClhxYVZHUWFrQTFCZnpSVXA1L2FUblNXd01NTlhpRWhwcWlock85UGZmdDVsZHZnaVJkU1V0UEowNXBQV0ZrdzcKeGpVV2ZabTNaRmgvQm93SDlKcEw1Yk0vemdQbnQ5V1RGWUZQMkRLNEFiOFdmb1lCRU5PMUh4dUZ0SWRRUktOUApTS01rVFh1UEdzaEtkSDlEVGxWRDhiM2NtalNsZ1NmZVdyZ3NHbWZlWVVES28xNStzV1YzZ2UyVnZzWTBTMmZuCi9seEltYkpoS0VnSC9Wb2lmMXUvejZhd0Rsdm01ME9uaEtiMHdyejhQbXlKaFdPbmhEM1VYVU82U01yK1dWUlcKd2RZb3JuZEhtc3FkY241MVNDbWNLbmZ5UzEvdFB5VTJnM3Z1YVNaVU5DYXc0U3gvQlNsYUV4VTdGenh1ZEV0ZQp5eHduendhQnVFWXlJZE5lL3NzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCaFU5V0JRdUw1YkJGK05EVytTNnpYQ1BkUG8KaytrVk1Nc2FWeE02TnZFRnFxcmord25aajZ0VmY4NEI0anVvR0RYMmNkWDhkTVY5dXVEZkN5SFpMZGJBaHQvbApSYkt1R1pZZFduT0I2ZG1ocS9VMHVDZ2FVVWxvNW1UMFh4YWJNbGppZS9DYUNpMmZNZy9LTVRGRXFYMFArSElMCnBSZkxGRmZ1QzZaVTV4aGV6dTFnK1ViaSs1amQvVHZBTTVnWnNTNnRNcGJzcXZ6MVhrVkE4aXVQQ1JKY1BPVlYKQkRUMUd3UWw0azNKU3RTckNxUHM2MDFGYXFCQm00YW5CaHFLaTd1WnlJbGpCUklCM0Q2bTQ3NlkxSlF5WlJyKwpndjJtRkxmVFRqNEc4a1FWRDJkdDkvMlVhZWdsVi94TU14VmZOdVN5WVdBelhvQU5aQzdjSnlyT2JERT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      sidecar-injection: enabled
