apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
  namespace: glin-ap31312mp00875-dev-platform-namespace
data:
  sidecarconfig.yaml: |
    containers:
    - name: fluentbit
      image: fluent/fluent-bit
      env:
      - name: FLUENTD_HOST
        value: logaggreg.glin-ap31312plcpfld-dev-platform-namespace.global
      envFrom:
      - configMapRef:
          name: sidecar-configmap
      volumeMounts:
        - name: shared-log
          mountPath: /var/log/platform
      resources:
        requests:
          memory: "0.04Gi"
          cpu: "0.05"
        limits:
          memory: "0.4Gi"
          cpu: "0.2"
    - name: events-sidecar
      image: busybox
      env:
      - name: PLATFORM_CONTAINER_NAME
        value: event-container
      envFrom:
      - configMapRef:
          name: fluentbit-configmap
      resources:
        requests:
          memory: "0.04Gi"
          cpu: "0.05"
        limits:
          memory: "0.4Gi"
          cpu: "0.2"
      command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]        
    volumes:
    - name: shared-log
      emptyDir: {}