apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-cfg
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Values.appname }}-certificate
  labels:
    app: memulesidecarinject
webhooks:
- name: memulesidecar.glin-ap31312mp00875-dev-platform-namespace.svc
  failurePolicy: Fail
  clientConfig:
    service:
      name: memulesidecar
      namespace: glin-ap31312mp00875-dev-platform-namespace
      path: "/mutate"
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  namespaceSelector:
    matchLabels:
      enel-sidecar-injector: enabled
