# Default values for annotation-injector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appname: sidecar-injector
namespace: mutating-webhook
replicaCount: 1

image:
  repository: sbenfa/sidecar-injector
  tag: latest
  pullPolicy: Always

tls:
  secret: sidecar-injector-certs

sidecar:
  config: sidecar-injector-webhook-configmap

application:
  namespace: 95fa13ec-78c7-4b9c-a73a-262a94aa4594

service:
  port: 443
  targetPort: 8443